api.directory=/home/ubuntu/Altair-Services/src/main/resources/static/api
reports.html=/home/ubuntu/Altair-Services/src/main/resources/static/api/reports/htmlextra
reports.xml=/home/ubuntu/Altair-Services/src/main/resources/static/api/reports/xml
bash.scripts=/home/ubuntu/Altair-Services/src/main/resources/static/api/bash-scripts

node.path=/home/ubuntu/.nvm/versions/node/v18.18.2/bin/node
newman.path=/home/ubuntu/.nvm/versions/node/v18.18.2/bin/newman
